### ISSUE TITLE
batt_read_voltage_simple' was not declared

### ISSUE THREAD

**Issue by roberbike** [levycarneiro/ESP32-Utils#1]
Hello.
I am trying to compile your sketch with platformio, and I get the following error:
src/main.cpp:29:22: error: 'batt_read_voltage_simple' was not declared in this scope
     float batt_vol = batt_read_voltage_simple (pin);

Cna you help me?

**Comment by levycarneiro** [comment]
Maybe try moving the function to before where it's called, so before setup().

**Comment by roberbike** [comment]
Yes. Now it is running.
Thanks
